### ISSUE TITLE
animation to stickyness?

### ISSUE THREAD

**Issue by RongBranovate** [sierraindiagolf/sig-sticky-header#1]
Hi, thanks for the directive, its smooth and simple.

do you intend to add animation to the stickyness? 
Maybe like a small fade in (if there's color change from `sig-sh-original` to `sig-sh-fixed`)?

thanks.

**Comment by RongBranovate** [comment]
Of course you can always just style your element:

``` css
#header {
    -webkit-transition: all 0.3s ease;
    -moz-transition: all 0.3s ease;
    -o-transition: all 0.3s ease;
    transition: all 0.3s ease;
}
```
